[phases.setup]
nixPkgs = ["nodejs-18_x", "python311"]

[phases.install]
cmds = [
"npm install --prefix frontend",
"python -m venv /opt/venv",
"/opt/venv/bin/pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "/opt/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT --chdir backend"