[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "gcc-unwrapped", "wkhtmltopdf"]

[phases.install]
cmds = [
  "npm install --prefix frontend",
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "bash -c 'export LD_LIBRARY_PATH=/root/.nix-profile/lib:$LD_LIBRARY_PATH && cd backend && /opt/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT'"
